[supabase]
url = "https://hmrftqougofiigklkave.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtcmZ0cW91Z29maWlna2xrYXZlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDcyMzc0MCwiZXhwIjoyMDYwMjk5NzQwfQ.v1nKYSogiel64zj4CHgfN0YzCtniFDXwjJxtUl4hEEo"
[sharepoint]
client_id = "8e291ba2-a8ad-4111-ad84-3138d22964c8"
client_secret = "GAx8Q~Nx.H6ywQT0.ya0s9pyoQC.5YMIitshxc7s"
tenant_id = "d4839413-8dc6-4de7-8470-f9fad33078d5"
site_url = "https://cocoasourcech.sharepoint.com/sites/EXPORTTRACA"
library_name = "Shared Documents"